"""adde some destination related fields to the data request model

Revision ID: 0ff87be72319
Revises: ff78c135a8ae
Create Date: 2019-10-08 08:10:10.300032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ff87be72319'
down_revision = 'ff78c135a8ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_request', sa.Column('dtype', sa.String(length=32), nullable=False))
    op.add_column('data_request', sa.Column('endpoint', sa.String(length=255), nullable=False))
    op.drop_constraint('data_request_destination_id_fkey', 'data_request', type_='foreignkey')
    op.drop_column('data_request', 'destination_id')
    op.drop_table('destination')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dest_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('uri', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='destination_pkey')
    )
    op.add_column('data_request', sa.Column('destination_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('data_request_destination_id_fkey', 'data_request', 'destination', ['destination_id'], ['id'])
    op.drop_column('data_request', 'endpoint')
    op.drop_column('data_request', 'dtype')
    # ### end Alembic commands ###
