"""added Schema model

Revision ID: 223b73553653
Revises: d473f082a6b4
Create Date: 2019-10-05 10:49:51.661513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223b73553653'
down_revision = 'd473f082a6b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['org_person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_schema',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('schema', sa.JSON(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['org_person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_schema')
    op.drop_table('dataset')
    # ### end Alembic commands ###
