"""added org sector model

Revision ID: 8c4b6bcd0044
Revises: a2ac521943e5
Create Date: 2019-10-04 09:04:56.658527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c4b6bcd0044'
down_revision = 'a2ac521943e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_sector',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sector', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('org_client', sa.Column('sector_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'org_client', 'org_sector', ['sector_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'org_client', type_='foreignkey')
    op.drop_column('org_client', 'sector_id')
    op.drop_table('org_sector')
    # ### end Alembic commands ###
