"""added org person model

Revision ID: c43f2f13bb95
Revises: 8c4b6bcd0044
Create Date: 2019-10-04 09:12:31.735972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c43f2f13bb95'
down_revision = '8c4b6bcd0044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_person',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstname_th', sa.String(length=255), nullable=True),
    sa.Column('lastname_th', sa.String(length=255), nullable=True),
    sa.Column('firstname_en', sa.String(length=255), nullable=True),
    sa.Column('lastname_en', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['org_client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('org_person')
    # ### end Alembic commands ###
