"""set firstname and lastname eng as required

Revision ID: ff78c135a8ae
Revises: 40fe4ff393b3
Create Date: 2019-10-06 08:57:50.891484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff78c135a8ae'
down_revision = '40fe4ff393b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('org_person', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('org_person', 'firstname_en',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('org_person', 'lastname_en',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('org_person', 'lastname_en',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('org_person', 'firstname_en',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('org_person', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
